comandos/urls.py
from django.contrib import admin
from django.urls import path , include
from soldiers import views
from django.conf import settings
from django.conf.urls.static import static

#Front config
admin.site.site_title = "Comandos Administrador"
admin.site.site_header = "Administración Comandos"

urlpatterns = [
    #Django Jet admin
    path('jet/', include('jet.urls', 'jet')),
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    #Django normal admin
    path('admin/', admin.site.urls),
    #Soldiers app's
    path("soldiers/", include("soldiers.urls")),
    #Home
    path('', views.home, name='home'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

soldiers/urls.py
from django.urls import path
from . import views

app_name= "soldiers"
urlpatterns = [
    path("home/", views.home, name='home'), #Visualiza la página principal que visualizaran los clientes.
    path("services/", views.services, name='services'), #Visualiza la página principal que visualizaran los clientes.
    path("plants/", views.plants, name='plants'), #Visualiza la página principal que visualizaran los clientes.

    path("check/", views.phoneRegister, name='check'), #Obtiene y envia el numero de celular para filtrar a partir de el.
    path("api/alerts/", views.asisRegister), #Guarda el intento de asistencia del usuario con o sin orden activa. 
    path("calendar/", views.viewCalendar, name='calendar'), #Envia un calendario apartir del cual se podra observar los registros por dia.
    #path("assistence/<str:year>/<str:month>/<str:day>", views.viewAsistenciabyDay), #Envia la lista de los registros segun el dia seleccionado en el calendario.
    path("api/calendar/<int:year>/<int:month>/<int:day>/to/<int:year2>/<int:month2>/<int:day2>", views.countCalendar), #Envia un conteo con el numero total de asistencias por categoria.
    path("cheaters/<int:year>/<int:month>/<int:day>/to/<int:year2>/<int:month2>/<int:day2>", views.viewTramposos), #Envia una lista con los usuarios "tramposos" por el rango de fecha puesto (que asisten luego de que su mensualidad haya vencido.)
    path("range/<int:year>/<int:month>/<int:day>/to/<int:year2>/<int:month2>/<int:day2>", views.viewRange), #Envia una lista con los registros hechos dentro de un periodo de tiempo.
    path("morosos/", views.viewMorosos, name='morosos'), #Envia una lista con los usuarios "morosos" (que van mas de los 15 dias pagos.)
    path("factura/<str:id>", views.viewInvoice), #Envia al template para visualizar la factura del usuario seleccionado.
    path("perfil/<str:id>", views.viewProfile),
]

soldiers/models.py
from django.db import models

# Create your models here.

class Soldier(models.Model):
    names = models.CharField(max_length=100,verbose_name= "Nombres:")
    lastNames = models.CharField(max_length=100,verbose_name= "Apellidos:")
    rh = models.CharField(max_length=3, blank=True,verbose_name= "RH:")
    age = models.SmallIntegerField(verbose_name= "Edad:")
    phoneNumber = models.CharField(max_length=20,unique=True,verbose_name= "No. celular:")
    email = models.EmailField(max_length=254,unique=True,verbose_name= "Email:")
    userPhoto = models.ImageField(upload_to ='photos/',max_length=100,verbose_name= "Foto:", blank=True)
    notes = models.TextField(blank=True,verbose_name= "Observaciones:")
    def __str__(self):
        return self.names + " " + self.lastNames

    def getId (self): 
        return self.id
    class Meta:
        verbose_name = "Soldado"
        verbose_name_plural  =  "Soldados"

class Measures(models.Model):
    soldier = models.ForeignKey(Soldier,on_delete=models.CASCADE)
    weight = models.FloatField(null=True,blank=True,verbose_name= "Peso:")
    height = models.FloatField(null=True,blank=True,verbose_name= "Altura:")
    shoulders = models.FloatField(null=True,blank=True,verbose_name= "Hombros:")
    abds = models.FloatField(null=True,blank=True,verbose_name= "Abdomen:")
    pectoral = models.FloatField(null=True,blank=True,verbose_name= "Pectorales:")
    leftBicep = models.FloatField(null=True,blank=True,verbose_name= "Bicep izquierdo:")
    rightBicep = models.FloatField(null=True,blank=True,verbose_name= "Bicep derecho:")
    leftForearm = models.FloatField(null=True,blank=True,verbose_name= "Antebrazo izquierdo:")
    rightForearm = models.FloatField(null=True,blank=True,verbose_name= "Antebrazo derecho:")
    leftLeg = models.FloatField(null=True,blank=True,verbose_name= "Pierna izquierda:")
    RightLeg = models.FloatField(null=True,blank=True,verbose_name= "Pierna derecha:")
    neck = models.FloatField(null=True,blank=True,verbose_name= "Cuello:")
    ass = models.FloatField(null=True,blank=True,verbose_name= "Gluteo:")

    class Meta:
        verbose_name = "Medida"
        verbose_name_plural  =  "Medidas"

from orders.models import Order
class Assistence(models.Model):
    soldier = models.ForeignKey(Soldier,on_delete=models.CASCADE,verbose_name= "Soldado:")
    registerDate = models.DateTimeField(auto_now_add=True)
    status = models.BooleanField(verbose_name = "Estado")
    order = models.ForeignKey(Order,on_delete=models.CASCADE,null=True,blank=True,verbose_name= "Factura:")
    def __str__(self):
        return "Asistencia No: " + str(self.id) + " || " + self.soldier.names

    class Meta:
        verbose_name = "Asistencia"
        verbose_name_plural  =  "Asistencias"

soldiers/forms.py
from django import forms

class RegisterForm(forms.Form):
    phone = forms.CharField(label="Telefono", max_length=15)

soldiers/views.py
import os
import datetime
from weasyprint import HTML
from django.conf import settings
from django.utils import timezone
from django.shortcuts import render
from .models import Soldier,Assistence
from products.models import ProductServ
from orders.models import Order,OrderDetail
from django.templatetags.static import static
from django.template.loader import render_to_string
from django.core.mail import EmailMultiAlternatives
from django.core.exceptions import ObjectDoesNotExist
from django.http import JsonResponse,HttpResponse,FileResponse
from django.contrib.auth.decorators import login_required,permission_required

# Create your views here.
#Lleva a las paginas que los clientes visualizarán.
def home(request):
    return render (request, "clientsPages/home.html")
def services(request):
    return render (request, "clientsPages/services.html")
def plants(request):
    return render (request, "clientsPages/plants.html")

@login_required
#Lleva a la pagina que habilita el registro de usuarios a partir de su numero celular.
def phoneRegister(request):
    return render (request, "phoneRegis.html")

@login_required
def asisRegister(request):
    now = timezone.localtime(timezone.now())
    phone = request.POST.get("phone")
    
    
    try:
        usr = Soldier.objects.get(phoneNumber=phone)#Obtiene el usuario al que le pertenece el No celular.
    except Soldier.DoesNotExist:
        return JsonResponse ({"message": 1, "info":None}, safe=False)#"El usuario aun no esta registrado."
    
    try:
        userInFactura = Order.objects.filter(soldier=usr).all() #Obtiene las ordenes que tiene el usuario vinculadas.
        suscriActivas = OrderDetail.objects.filter(order__in=userInFactura,endSuscription__gte=now).get()
    except ObjectDoesNotExist:
        suscriActivas = None

    asisExist = Assistence.objects.filter(
        registerDate__year=now.year,
        registerDate__month=now.month,
        registerDate__day=now.day,
        soldier=usr
    )
    try:
        dataUsr={"photo_url":usr.userPhoto.url,"nombreSold":usr.names,"apellidoSold":usr.lastNames,
             "dateEnd":suscriActivas.endSuscription}
    except:
        dataUsr={"photo_url":usr.userPhoto.url,"nombreSold":usr.names,"apellidoSold":usr.lastNames,
             "dateEnd":"No tiene una suscripción activa"}

    if asisExist.exists():
        return JsonResponse ({"message": 3, "info":dataUsr}, safe=False)#El usuario ya asistió el dia de hoy.
    elif suscriActivas:
        Assistence.objects.create(soldier=usr, status=True, order=suscriActivas.order, registerDate=now)
        return JsonResponse ({"message": 2, "info":dataUsr}, safe=False)#Registro satisfactorio.
    else: 
        Assistence.objects.create(soldier=usr, status=False, order=None, registerDate=now)
        return JsonResponse ({"message": 4, "info": dataUsr}, safe=False)#El usuario no tiene ninguna orden de suscripcion registrada.

@login_required
def viewCalendar(request):
    return render(request, "reports.html")

'''
def viewAsistenciabyDay(request, year, month, day):
    asistenciByDay = Assistence.objects.filter(registerDate__year=year, registerDate__month=month,registerDate__day=day)
    countByDay = asistenciByDay.count()
    assis2 = Assistence.objects.all()
    context = {
        "listaAsistencia": asistenciByDay,
    }
    return render (request, 'assistencebyday.html' ,context)
'''

@login_required
def countCalendar(request, year,month,day,year2,month2,day2):
    #Dias
    fecha1 = str(year)+'-'+str(month)+'-'+str(day)+' 00:00:00'
    fecha2 = str(year2)+'-'+str(month2)+'-'+str(day2)+' 23:59:59'

    rangeGeneral = Assistence.objects.filter(registerDate__range=(fecha1, fecha2)).count()
    rangeTramposos = Assistence.objects.filter(registerDate__range=(fecha1, fecha2),status=False).count()
    return JsonResponse ({"totalAsistencia": rangeGeneral, "totalTramposos": rangeTramposos}, safe=False)

@login_required
def viewTramposos(request, year,month,day,year2,month2,day2):
    #Dias
    date1 = str(year)+'-'+str(month)+'-'+str(day)+' 00:00:00'
    date2 = str(year2)+'-'+str(month2)+'-'+str(day2)+' 23:59:59'
    fecha1 = datetime.date(year,month,day)
    fecha2 = datetime.date(year2,month2,day2)

    tramp = Assistence.objects.filter(registerDate__range=(date1,date2),status=False).order_by('registerDate')
    context = {
        "fecha1": fecha1,
        "fecha2": fecha2,
        "trampososList": tramp
    }
    return render(request, 'tramposos.html',context)

@login_required
def viewRange(request,year,month,day,year2,month2,day2):
    #Dias
    fecha1 = datetime.date(year,month,day)
    fecha2 = datetime.date(year2,month2,day2)
    date1 = str(year)+'-'+str(month)+'-'+str(day)+' 00:00:00'
    date2 = str(year2)+'-'+str(month2)+'-'+str(day2)+' 23:59:59'

    #if date2 != date1:
    range = Assistence.objects.filter(registerDate__range=(date1,date2)).order_by('registerDate')
    context = {
        "fecha1": fecha1,
        "fecha2": fecha2,
        "rangeList": range
    }
    return render(request, 'rango.html',context)

@login_required
def viewMorosos(request):
    morosos = []
    paso1 = OrderDetail.objects.filter(product=2)
    for o in paso1:
        paso2 = (o.order.id)
        paso3 = Assistence.objects.filter(order=paso2).count()
        if paso3 > 12:
            dictmorosos = {"nombre": o.order.soldier.names, 'factura': o.order.id, 'fechaVencimiento': o.endSuscription,  "diasextra":paso3-12,"perfil":o.order.soldier.id}
            morosos.append(dictmorosos)
    context = {
        "morososList": morosos
    }
    return render (request,"morosos.html", context)

@login_required
def viewInvoice(request,id):
    # Invoice data
    logo_url = request.build_absolute_uri(static('images/logo.png'))
    data = Order.objects.filter(id=id).latest('id')
    nameItem = OrderDetail.objects.filter(order=id).get()#Pregunta si aca siempre buscaria la orden actual en la que esta.
    valueItem = ProductServ.objects.filter(name=nameItem.product).get()
    items = [
        {
            'producto':nameItem.product,
            'cantidad':nameItem.quantity,
            'valorProd':valueItem.price,   
        }
    ]
    total = sum([i['valorProd'] for i in items])

    try:

        email = EmailMultiAlternatives(
            subject = 'Bienvenido a la familia Comandos Gym',
            body = 'Hola ¿como estas? aqui esta tu factura',
            from_email = 'comandosgym@hotmail.com',
            to = [data.soldier.email],
        )

        info = {
            "numFactura":data.id,
            "fechaCreacion":data.creationDate.date,
            "client":data.soldier, 
            "pagoMeto":data.methodPayment,
            "items":items,
            "final":nameItem.endSuscription.date,
            "totalFactu":total,
            "logo":logo_url
        }

        # Create pdf file with template 'invTemplate.html' 
        html_string = render_to_string('invTemplate.html',info)
        pdf_file = HTML(string=html_string).write_pdf()

        # Create path folders if doesn't exist
        download_folder = os.path.join(settings.BASE_DIR, 'Media', 'Invoices')
        os.makedirs(download_folder, exist_ok=True)
        file_path = os.path.join(download_folder, f'Factura-{id}.pdf')

        # Put the pdf file on path Media/Invoices  
        with open(file_path, 'wb') as f: # <-- 'WB' means write binary
            f.write(pdf_file)

        # Create pdf file view and download it
        response = FileResponse(open(file_path,"rb"))
        response['Content-Disposition'] = f'attachment; filename="Factura-{id}.pdf"'

        # Attach pdf file to email
        email.attach_file(file_path)

        # Send mail
        email.send()
        return response

    except:

        email = EmailMultiAlternatives(
            subject = 'Bienvenido a la familia Comandos Gym',
            body = 'Hola ¿como estas? aqui esta tu factura',
            from_email = 'comandosgym@hotmail.com',
            to = [data.soldier.email],
        )

        info = {
            "numFactura":data.id,
            "fechaCreacion":data.creationDate.date,
            "client":data.soldier, 
            "pagoMeto":data.methodPayment,
            "items":items,
            "final":"No aplica.",
            "totalFactu":total,
            "logo":logo_url
        }

        # Create pdf file with template 'invTemplate.html' 
        html_string = render_to_string('invTemplate.html',info)
        pdf_file = HTML(string=html_string).write_pdf()

        # Create path folders if doesn't exist
        download_folder = os.path.join(settings.BASE_DIR, 'Media', 'Invoices')
        os.makedirs(download_folder, exist_ok=True)
        file_path = os.path.join(download_folder, f'Factura-{id}.pdf')

        # Put the pdf file on path Media/Invoices  
        with open(file_path, 'wb') as f: # <-- 'WB' means write binary
            f.write(pdf_file)
        
        # Create pdf file view and download it
        response = FileResponse(open(file_path,"rb"))
        response['Content-Disposition'] = f'attachment; filename="Factura-{id}.pdf"'

        # Attach pdf file to email
        email.attach_file(file_path)

        # Send mail
        email.send()
        return response

@login_required
def viewProfile(request,id):
    data = Soldier.objects.filter(id=id).get()
    try:
        ord = Order.objects.filter(soldier_id=id).latest('id')
        invoice = OrderDetail.objects.filter(order_id=ord.id).get()
        info = {"photo_url":data.userPhoto.url,"nombreSold":data.names,"apellidoSold":data.lastNames,"dateEnd":invoice.endSuscription.date,
            "rh":data.rh,"phone":data.phoneNumber,"age":data.age,"notes":data.notes}
        return render (request, "profile.html",info)
    except ObjectDoesNotExist:
        info = {"photo_url":data.userPhoto.url,"nombreSold":data.names,"apellidoSold":data.lastNames,"dateEnd":"No tiene una suscripción activa",

soldiers/templates/clientsPages/home.html
{% load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Comandos Gym</title>
    <link rel="stylesheet" href="{% static 'css/pageP.css' %}">
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'images/favicon.png' %}">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <!-- Bootstrap JS -->
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- Awesome Icon's CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css">
</head>
<header>
  <nav>
    <div id="nav">
      <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
          <a href="{% url 'soldiers:home' %}" class="d-flex align-items-center my-2 my-lg-0 me-lg-auto text-white text-decoration-none">
            <img class="bi me-2" width="120" height="85" src="{% static 'images/favicon.png' %}">
          </a>
          <ul class="nav col-12 col-lg-auto my-2 justify-content-center my-md-0 text-small">
            <li>
              <a href="{% url 'soldiers:home' %}" class="nav-link text-decoration-none" id="text-1">
                <svg class="bi d-block mx-auto mb-1" width="40" height="40" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path fill="#000000" d="M240.1 4.2c9.8-5.6 21.9-5.6 31.8 0l171.8 98.1L448 104l0 .9 47.9 27.4c12.6 7.2 18.8 22 15.1 36s-16.4 23.8-30.9 23.8H32c-14.5 0-27.2-9.8-30.9-23.8s2.5-28.8 15.1-36L64 104.9V104l4.4-1.6L240.1 4.2zM64 224h64V416h40V224h64V416h48V224h64V416h40V224h64V420.3c.6 .3 1.2 .7 1.8 1.1l48 32c11.7 7.8 17 22.4 12.9 35.9S494.1 512 480 512H32c-14.1 0-26.5-9.2-30.6-22.7s1.1-28.1 12.9-35.9l48-32c.6-.4 1.2-.7 1.8-1.1V224z"/></svg>
                Inicio
              </a>
            </li>
            <li>
              <a href="{% url 'soldiers:services' %}" class="nav-link text-white">
                <svg class="bi d-block mx-auto mb-1" width="40" height="40" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 640 512"><path fill="#ffffff" d="M96 64c0-17.7 14.3-32 32-32h32c17.7 0 32 14.3 32 32V224v64V448c0 17.7-14.3 32-32 32H128c-17.7 0-32-14.3-32-32V384H64c-17.7 0-32-14.3-32-32V288c-17.7 0-32-14.3-32-32s14.3-32 32-32V160c0-17.7 14.3-32 32-32H96V64zm448 0v64h32c17.7 0 32 14.3 32 32v64c17.7 0 32 14.3 32 32s-14.3 32-32 32v64c0 17.7-14.3 32-32 32H544v64c0 17.7-14.3 32-32 32H480c-17.7 0-32-14.3-32-32V288 224 64c0-17.7 14.3-32 32-32h32c17.7 0 32 14.3 32 32zM416 224v64H224V224H416z"/></svg>
                Servicios
              </a>
            </li>
            <li>
              <a href="{% url 'soldiers:plants' %}" class="nav-link text-white">
                <svg class="bi d-block mx-auto mb-1" width="40" height="40" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"><path fill="#ffffff" d="M80 80V192c0 2.5 1.2 4.9 3.2 6.4l51.2 38.4c6.8 5.1 10.4 13.4 9.5 21.9L133.5 352H85.2l9.4-85L54.4 236.8C40.3 226.2 32 209.6 32 192V72c0-22.1 17.9-40 40-40H376c22.1 0 40 17.9 40 40V192c0 17.6-8.3 34.2-22.4 44.8L353.4 267l9.4 85H314.5l-10.4-93.3c-.9-8.4 2.7-16.8 9.5-21.9l51.2-38.4c2-1.5 3.2-3.9 3.2-6.4V80H304v24c0 13.3-10.7 24-24 24s-24-10.7-24-24V80H192v24c0 13.3-10.7 24-24 24s-24-10.7-24-24V80H80zm4.7 384H363.3l-16.6-32H101.2L84.7 464zm271.9-80c12 0 22.9 6.7 28.4 17.3l26.5 51.2c3 5.8 4.6 12.2 4.6 18.7c0 22.5-18.2 40.8-40.8 40.8H72.8C50.2 512 32 493.8 32 471.2c0-6.5 1.6-12.9 4.6-18.7l26.5-51.2C68.5 390.7 79.5 384 91.5 384h265zM208 288c-8.8 0-16-7.2-16-16V224c0-17.7 14.3-32 32-32s32 14.3 32 32v48c0 8.8-7.2 16-16 16H208z"/></svg>
                Instalaciones
              </a>  
            </li>
          </ul>
        </div>
      </div>
    </div>
  </nav>
</header>
<body>
  <div id="carousel" class="carousel slide">
    <div class="carousel-indicators">
      <button type="button" data-bs-target="#carousel" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
      <button type="button" data-bs-target="#carousel" data-bs-slide-to="1" aria-label="Slide 2"></button>
      <button type="button" data-bs-target="#carousel" data-bs-slide-to="2" aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img src="{% static 'images/gray.jpg' %}" class="d-block w-100" width="100%" height="510">
        <div class="carousel-caption d-none d-md-block">
          <h5>Primer texto</h5>
          <p>Lorem ipsum dolor sit amet.</p>
        </div>
      </div>
      <div class="carousel-item">
        <img src="{% static 'images/gray.jpg' %}" class="d-block w-100" width="100%" height="510">
        <div class="carousel-caption d-none d-md-block">
          <h5>Segundo texto</h5>
          <p>Lorem ipsum dolor sit amet.</p>
        </div>
      </div>
      <div class="carousel-item">
        <img src="{% static 'images/gray.jpg' %}" class="d-block w-100" width="100%" height="510">
        <div class="carousel-caption d-none d-md-block">
          <h5>Tercer texto</h5>
          <p>Lorem ipsum dolor sit amet.</p>
        </div>
      </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carousel" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carousel" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>
  <hr class="line">
  <div id="map">
      <iframe 
        src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3975.1299094421674!2d-74.09847632622902!3d4.9179238950580135!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x8e40799038babba3%3A0x9cd1d9c5c5d819d5!2sComandos%20Gym!5e0!3m2!1ses!2sco!4v1707346456078!5m2!1ses!2sco" 
        width="100%" height="400" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade">
      </iframe>
  </div>
</body>
<div id="Footer" class="container-fluid">
  <div class="container">
    <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
      <p class="col-md-4 mb-0 text-body-secondary">© Comandos Gym 2024</p>
      <ul class="nav col-md-4 justify-content-end">
        <li class="nav-item"><a href="https://www.instagram.com/comandos_gym/" class="nav-link px-2 text-body-secondary"><i class="fa-brands fa-instagram fa-xl"></i></a></li>
        <li class="nav-item"><a href="https://www.facebook.com/ComandosGymTabio" class="nav-link px-2 text-body-secondary"><i class="fa-brands fa-facebook fa-xl"></i></a></li>
        <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary"><i class="fa-brands fa-whatsapp fa-xl"></i></a></li>
      </ul>
    </footer>
  </div>
</div>
</html>