comandos/urls.py
from django.contrib import admin
from django.urls import path , include
from soldiers import views
from django.conf import settings
from django.conf.urls.static import static

#Front config
admin.site.site_title = "Comandos Administrador"
admin.site.site_header = "Administración Comandos"

urlpatterns = [
    #Django Jet admin
    path('jet/', include('jet.urls', 'jet')),
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    #Django normal admin
    path('admin/', admin.site.urls),
    #Soldiers app's
    path("soldiers/", include("soldiers.urls")),
    #Home
    path('', views.home, name='home'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

soldiers/urls.py
from django.urls import path
from . import views

app_name= "soldiers"
urlpatterns = [
    path("home/", views.home, name='home'), #Visualiza la página principal que visualizaran los clientes.
    path("services/", views.services, name='services'), #Visualiza la página principal que visualizaran los clientes.
    path("plants/", views.plants, name='plants'), #Visualiza la página principal que visualizaran los clientes.

    path("check/", views.phoneRegister, name='check'), #Obtiene y envia el numero de celular para filtrar a partir de el.
    path("api/alerts/", views.asisRegister), #Guarda el intento de asistencia del usuario con o sin orden activa. 
    path("calendar/", views.viewCalendar, name='calendar'), #Envia un calendario apartir del cual se podra observar los registros por dia.
    #path("assistence/<str:year>/<str:month>/<str:day>", views.viewAsistenciabyDay), #Envia la lista de los registros segun el dia seleccionado en el calendario.
    path("api/calendar/<int:year>/<int:month>/<int:day>/to/<int:year2>/<int:month2>/<int:day2>", views.countCalendar), #Envia un conteo con el numero total de asistencias por categoria.
    path("cheaters/<int:year>/<int:month>/<int:day>/to/<int:year2>/<int:month2>/<int:day2>", views.viewTramposos), #Envia una lista con los usuarios "tramposos" por el rango de fecha puesto (que asisten luego de que su mensualidad haya vencido.)
    path("range/<int:year>/<int:month>/<int:day>/to/<int:year2>/<int:month2>/<int:day2>", views.viewRange), #Envia una lista con los registros hechos dentro de un periodo de tiempo.
    path("morosos/", views.viewMorosos, name='morosos'), #Envia una lista con los usuarios "morosos" (que van mas de los 15 dias pagos.)
    path("factura/<str:id>", views.viewInvoice), #Envia al template para visualizar la factura del usuario seleccionado.
    path("perfil/<str:id>", views.viewProfile),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <link rel="shortcut icon" type="image/x-icon" href="{% static 'images/favicon.png' %}">
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <!-- Bootstrap JS -->
        <script src="{% static 'js/popper.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
        <!-- JQuery JS -->
        <script src="{% static 'js/jquery.min.js' %}"></script>
        <!-- Awesome Icon's CSS -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css">
    </head>
    <body>
        <div id="Nav">
          <nav class="navbar navbar-expand-lg bg-body-tertiary">
            <div class="container-fluid">
              <a class="navbar-brand" href="{% url 'soldiers:home' %}"><i class="fa-solid fa-landmark"></i> Home</a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'soldiers:check' %}"><i class="fa-regular fa-pen-to-square"></i> Registro Asistencia</a>
                  </li>
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                      <i class="fa-solid fa-bullhorn"></i> Reportes</a>
                    <ul class="dropdown-menu">
                      <li><a class="dropdown-item" href="{% url 'soldiers:morosos' %}"><i class="fa-solid fa-bugs"></i> Morosos</a></li>
                      <li><hr class="dropdown-divider"></li>
                      <li><a class="dropdown-item" href="{% url 'soldiers:calendar' %}"><i class="fa-solid fa-calendar-days"></i> Calendario</a></li>
                    </ul>
                  </li>
                </ul>
                <span class="navbar-text">
                 <i class="fa-solid fa-dumbbell fa-bounce"></i> Comandos Gym
                </span>
              </div>
            </div>
          </nav>
        </div>
        <div id="Main" class="container" >
                {% block content %}
                {% endblock %}
            </div> 
        </div>
        <div id="Footer" class="container-fluid">
          <div class="container">
            <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
              <p class="col-md-4 mb-0 text-body-secondary">© Comandos Gym 2024</p>
              <ul class="nav col-md-4 justify-content-end">
                <li class="nav-item"><a href="{% url 'soldiers:home' %}" class="nav-link px-2 text-body-secondary"><i class="fa-solid fa-landmark fa-xl"></i></a></li>
                <li class="nav-item"><a href="https://www.instagram.com/comandos_gym/" class="nav-link px-2 text-body-secondary"><i class="fa-brands fa-instagram fa-xl"></i></a></li>
                <li class="nav-item"><a href="https://www.facebook.com/ComandosGymTabio" class="nav-link px-2 text-body-secondary"><i class="fa-brands fa-facebook fa-xl"></i></a></li>
                <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary"><i class="fa-brands fa-whatsapp fa-xl"></i></a></li>
                <li class="nav-item"><a href="/admin/" class="nav-link px-2 text-body-secondary"><i class="fa-solid fa-user-tie fa-xl"></i></a></li>
              </ul>
            </footer>
          </div>
        </div>
    </body>
</html>